# APPLICATION NAME
spring.application.name=SkillLMS

# PORT
server.port=8901

# CONTEXT-PATH
server.servlet.context-path=/soul
client.redirect-url=http://localhost:3000/lms/

# DATA SOURCE (ORACLE)
#spring.datasource.url=jdbc:oracle:thin:@13.126.157.180:15024:MAROGYAM
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.username=emrmaster
#spring.datasource.password=emrmaster123

# LOCAL TEST
#spring.datasource.url=jdbc:postgresql://localhost:5432/lmsdb
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=postgres
#spring.datasource.password=1234

#DATA SOURCE (POSTGRES) - Local Host 

spring.datasource.url=jdbc:postgresql://localhost:5432/lmsdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=lms
spring.datasource.password=lms123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# DATA SOURCE (POSTGRES) - Neon DB 

#spring.datasource.url=jdbc:postgresql://ep-nameless-recipe-a1pfemun-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_g4kSvT0MuJla
#spring.datasource.hikari.maximum-pool-size=5
#spring.datasource.hikari.minimum-idle=0
#spring.datasource.hikari.idle-timeout=10000
#spring.datasource.hikari.connection-timeout=10000
#spring.datasource.hikari.max-lifetime=250000
#spring.datasource.hikari.keepalive-time=30000
#spring.datasource.hikari.validation-timeout=5000
#spring.datasource.hikari.leak-detection-threshold=0
#spring.datasource.hikari.data-source-properties.reWriteBatchedInserts=true
#spring.datasource.hikari.data-source-properties.tcpKeepAlive=true
#spring.datasource.hikari.data-source-properties.ApplicationName=SkillLMS


# DATA SOURCE (MYSQL)
#spring.datasource.url=jdbc:mysql://localhost:3306/lms
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=1234

# JPA / HIBERNATE
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

# LOGGING
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN

# ACTUATOR AND METRICS
management.endpoints.web.exposure.include = info,health,metrics

# THYMELEAF CONFIGURATION
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/views/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.cache=false
spring.main.allow-bean-definition-overriding=true

#for loading application-dev.properties
spring.profiles.active=dev
spring.devtools.livereload.enabled=false

# LOGS
logging.file.path=logs/
logging.file.name=logs/application-${PID}.log

#JWT private key
jwt.secretKey=PtEVtEFIknIhoXzJ3BViqEIAO/S7vyTi+o/cBhsggX9OpRCJMkEgoygVHzLvlu2Q0Y/p26Th7sk6ASlmDfbgXw==
jwt.expiryTime=86400000
# SpringDoc properties
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui

# GOOGLE CREDENTIALS
#spring.google.clientId = your-google-client-id.apps.googleusercontent.com
spring.google.clientId = ${GOOGLE_CLIENT_ID:}
#spring.google.projectId = ehrsoullimited
spring.google.projectId = lms-project-424306
#spring.google.clientSecret = your-google-client-secret
spring.google.clientSecret = ${GOOGLE_CLIENT_SECRET:}
spring.google.redirectUri = http://localhost:8901/soul/
#spring.google.redirectUri = http://52.66.254.50:8988/
spring.google.tokenUri = oauth2.googleapis.com/token","auth_provider_x509_cert_url

# Google OIDC configuration
#spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
#spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.scope=openid, profile, email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8901/soul/login/oauth2/code/google
spring.security.oauth2.client.registration.google.client-name=Google

# OAuth2 Provider Configuration
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.jwk-set-uri=https://www.googleapis.com/oauth2/v3/certs
spring.security.oauth2.client.provider.google.user-name-attribute=sub

#EMAIL CREDENTIALS
spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = testsoul293@gmail.com
spring.mail.password = mlsoumsqievqxukp
spring.mail.properties.mail.smtp.starttls.enable = true
spring.mail.properties.mail.smtp.starttls.required = true
spring.mail.properties.mail.smtp.auth = true

# MULTIPART FILE
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB

#FILE UPLOAD PATH
server.file.upload.path=C:/users/rutur/downloads/

# BUCKET NAME
cloud.bucket.name=" "

# BINARY FILE PATH
spring.file.path=" "

# To ignore JSON fields hibernateLazyInitializer and handler from serialization
spring.jackson.serialization.fail-on-empty-beans=false
